### PR TITLE
compress write_android_native_libs

### PR DESCRIPTION
**Pull request by tofutim**
how about this, use a loop over arch to build the write_android_native_libs

### CODE REVIEW

**Comment by ericsink** [comment]
👍

**Comment by tofutim** [comment]
how would you feel about combining write_android_native_libs and write_android_native_libs_sqlcipher and adding a 'what' argument to it?

**Comment by tofutim** [comment]
also, do you prefer tabs or spaces, or don't care?

**Comment by ericsink** [comment]
More big picture thoughts:  This is a good pull request.  It makes the code better.

But it still fits in the category of "trying to convince me to accept changes before you have implemented the feature you want".  That's not the worst problem in the world.

To express it another way:  This pull request is "good", but it is neither "urgent" nor "important".  It doesn't fix a bug.  It doesn't add functionality.  It just makes the code better.

My only concern about this kind of pull request is my own time constraints.  If lots of these are coming, I will find it hard to keep up.  Collaborating with you at each step while you implement the feature you want would be more work for me than just implementing it myself.  :-)

**Comment by ericsink** [comment]
Spaces.  Tabs are evil.  That said, the code in this repo is not at all consistent.  In some places the indentation and formatting is an absolute disaster.  And I've been reluctant to run it through a formatter because I lose the ability to diff across that boundary.

**Comment by tofutim** [comment]
You can diff ignoring whitespace changes. 
Looks you like tab = 4 spaces? I'll change the changes.

**Pull request closed without merging**
