### PR TITLE
Expose sqlite3_bind_blob overload which takes the length of the blob to bind to.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Addresses part of issue raised in: https://github.com/ericsink/SQLitePCL.raw/issues/135

Tagging @ericsink .  Note: i'm unclear on how to build locally.  Can you advise on how to best do that?

### CODE REVIEW

**Comment by ericsink** [comment]
Building SQLitePCL.raw is, er, tricky.

Basically, gen_build.cs compiles to something that generates all the project files.

Take a look at go.ps1 for an example.

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Comment by CyrusNajmabadi** [comment]
Followup question.  What's your release schedule generally like?  Thanks!

**Comment by ericsink** [comment]
I plan to do a release in the next few days.  I just want a bit more testing first.

More generally, I tend to do a release whenever something is urgent, or when I have accumulated a nice batch of non-urgent changes.

**Comment by CyrusNajmabadi** [comment]
Awesome.  Thanks for your help!

**Pull request merged**
