### PR TITLE
Add implementation for sqlite3_db_config, sqlite3_[soft/hard]_heap_limit64 and sqlite3_limit

### PR DESCRIPTION
**Pull request by filipnavara**

### CODE REVIEW

**Comment by filipnavara** [comment]
I didn't include the regenerated code in the commit to make it easier to review and rebase if needed.

**Comment by filipnavara** [comment]
@ericsink Sorry to bother you but any chance to move forward with this?

**Comment by ericsink** [comment]
Sorry for the delay.  A little procrastination piles up fast.  :-)

The implementation looks good.  Could you add test cases?  See src/common/tests_xunit.cs

Thanks!

**Comment by filipnavara** [comment]
Thanks! I'll look into adding the test cases once I get a free day, hopefully soon.

**Comment by springy76** [comment]
I nearly can't await `SQLITE_DBCONFIG_NO_CKPT_ON_CLOSE`

**Comment by pavel-faltynek** [comment]
Hey, I have added the tests and performed small fix in the variable arguments definition and rebased to the current master (which rendered the code uncompilable because of the snapshot stuff). Anyway, @ericsink, would you mind to check it, whether it is closer to your expectations? Thank you.

**Comment by filipnavara** [comment]
@ericsink My colleague fixed the varargs definitions and added basic tests. Unfortunately the `master` branch currently doesn't build because the CIL provider binaries are missing. We tested it on earlier version without the snapshots API that was pulled from the published NuGet and it seems to pass just fine.

As before the generated sources are NOT committed to make the diff viewing easier.

**Pull request merged**
