### PR TITLE
Added a few changes to make the library .NET 4.0 compatible

### PR DESCRIPTION
**Pull request by borrrden**
Only a few changes needed.  Needs review for how to proceed (separate 4.0 target?  target 4.0 instead of 4.5?).

### CODE REVIEW

**Comment by ericsink** [comment]
No surprises here.  I'm pretty sure I'll work this in as a separate 4.0 target.  Thanks.

**Comment by ericsink** [comment]
Although I didn't merge this PR, I implemented the same thing in 0.8.0.  If that looks okay, I assume we could close this one.

**Comment by borrrden** [comment]
Actually I'm not as interested in it anymore.  This was back when we thought Unity 5 was getting .NET 4 support.  We actually had to retarget to 3.5, and I assume you are not interested in supporting that as well eh? ;)  I've made custom non-PCL builds of this library for my purposes but I'd be happy to share what I did if you are curious.

**Comment by ericsink** [comment]
Was going to close this, but then I noticed some recent activity.  It looks like the net40 issue is no longer an issue, but net35 might be.  I haven't looked at net35 compatibility at all.  No promises there.  Anyway, should this PR be closed?

**Comment by borrrden** [comment]
The activity is just because I'm messing around in my own repo.  It has no bearing on this PR, which can be closed.  There is no PCL profile that include .NET 3.5 so I assume that you shouldn't attempt to add in stuff for it.  I've forked the repo to couchbasedeps and included the changes I needed to make to get this to work on .NET 3.5 in case you are simply curious.

**Pull request closed without merging**
