### PR TITLE
Avoid heap allocation for small strings in sqlite3_bind_text

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
@ericsink For your consideration.  Not sure how tests work here.  Would def like to ensure this actually gets coverage.  Thanks!

### CODE REVIEW

**Comment by ericsink** [comment]
I'll run tests and get back to you.

**Comment by ericsink** [comment]
I'm seeing a failing test case when the string is zero-length.  I put in a quickie fix for that and I'm going to run the EFCore test suite, which is much more comprehensive.

**Comment by ericsink** [comment]
After my tweak for the empty string case, this passes all my tests and the EF Core tests.

**Comment by sharwell** [comment]
@ericsink Is there a follow-up issue for modifying this method to call SQLite's UTF-16 method instead of relying on managed code to do the conversion?

**Comment by ericsink** [comment]
@sharwell Not yet.  Sorry I'm a bit slow on responses -- I'm swamped with another project today.  Feel free to log such an issue.  I don't plan any objections, although I do want to make sure I understand exactly how the underlying C API works.

**Pull request merged**
