### PR TITLE
net35 goes to env, but the rest should fall back from netstandard11 t…

### PR DESCRIPTION
**Pull request by tofutim**
…o profile259 to profile111

Please see if there is something to do this. Currently everything gets mapped to its own env because all core's are available.

### CODE REVIEW

**Comment by ericsink** [comment]
Yeah, as I said in my comment on #128, this is an area I have planned to investigate further. Your change looks generally on the right track.

**Comment by tofutim** [comment]
there is some compilation issues with macos - I'm not sure what is going on but will debug some more; when macos references the netstandard11 library you get a lot of errors like

ted [D:\Loqu8\Db\SQLitePCL.raw\bld\SQLitePCLRaw.core.netstandard11\SQLitePCLRaw.core.netstandard11.csproj]
  D:\Loqu8\Db\SQLitePCL.raw\src\cs\raw.cs(267,60): error CS0518: Predefined type 'System.Int32' is not defined or impor
ted [D:\Loqu8\Db\SQLitePCL.raw\bld\SQLitePCLRaw.core.netstandard11\SQLitePCLRaw.core.netstandard11.csproj]
  D:\Loqu8\Db\SQLitePCL.raw\src\cs\raw.cs(268,60): error CS0518: Predefined type 'System.Int32' is not defined or impor
ted [D:\Loqu8\Db\SQLitePCL.raw\bld\SQLitePCLRaw.core.netstandard11\SQLitePCLRaw.core.netstandard11.csproj]
  D:\Loqu8\Db\SQLitePCL.raw\src\cs\raw.cs(271,42): error CS0518: Predefined type 'System.Int32' is not defined or impor
ted [D:\Loqu8\Db\SQLitePCL.raw\bld\SQLitePCLRaw.core.netstandard11\SQLitePCLRaw.core.netstandard11.csproj]
  D:\Loqu8\Db\SQLitePCL.raw\src\cs\raw.cs(272,42): error CS0518: Predefined type 'System.Int32' is not defined or impor
ted [D:\Loqu8\Db\SQLitePCL.raw\bld\SQLitePCLRaw.core.netstandard11\SQLitePCLRaw.core.netstandard11.csproj]
  D:\Loqu8\Db\SQLitePCL.raw\src\cs\sqlite3_bait.cs(37,31): error CS0518: Predefined type 'System.String' is not defined
 or imported [D:\Loqu8\Db\SQLitePCL.raw\bld\SQLitePCLRaw.core.netstandard11\SQLitePCLRaw.core.netstandard11.csproj]
  D:\Loqu8\Db\SQLitePCL.raw\src\cs\sqlite3_bait.cs(39,9): error CS0518: Predefined type 'System.Void' is not defined or
 imported [D:\Loqu8\Db\SQLitePCL.raw\bld\SQLitePCLRaw.core.netstandard11\SQLitePCLRaw.core.netstandard11.csproj]

**Comment by tofutim** [comment]
I think there might be some issues with Xamarin.Mac and netstandard11. I see errors like

```
  D:\Loqu8\Db\SQLitePCL.raw\src\cs\ugly.cs(942,24): error CS0012: The type 'Object' is defined in an assembly that is n
ot referenced. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b
03f5f7f11d50a3a'. [D:\Loqu8\Db\SQLitePCL.raw\bld\SQLitePCLRaw.ugly.profile136\SQLitePCLRaw.ugly.profile136.csproj]
```

**Comment by ericsink** [comment]
Yes, I'm familiar with that System.Runtime issue.  The same thing happened the last few times I tried doing what you are trying to do, and that is one of the reasons why I decided to defer this and work on it later.

That's still true.  As I said, you are investigating something I know about, and you are on the right track, but I'm not dealing with this issue right now.

This pull request will not result in something that I will merge.  I'm closing it.

**Pull request closed without merging**
