### PR TITLE
sqlite3_stmt_status

### PR DESCRIPTION
**Pull request by bordoley**

### CODE REVIEW

**Comment by bordoley** [comment]
rebased to master.

**Comment by ericsink** [comment]
Darn it.  After merging the other two status-related PRs, this one now has conflicts.

At the risk of setting new records for laziness, could you re-rebase this one?  :-)

Thanks.

**Comment by bordoley** [comment]
yeah. Can I merge this one with
https://github.com/ericsink/SQLitePCL.raw/pull/12 into a single PR to avoid
further conflicts? I can do the rebase tonight.

Dave

**Comment by ericsink** [comment]
Yeah, that's fine.

**Pull request merged**
