### PR TITLE
Return null from db_filename for memory databases.

### PR DESCRIPTION
**Pull request by bordoley**
Fixes: https://github.com/ericsink/SQLitePCL.raw/issues/13

### CODE REVIEW

**Comment by ericsink** [comment]
This PR has 2 problems that need to be resolved (by bordoley before) | (by myself after) merging it.

(1)  Pedantic nitpick:  I would like to catch the null (or rather int64 zero or IntPtr.zero) coming from the native code rather than running it through new IntPtr() and then from_utf8() and then checking the resulting non-null string .Length against zero and then converting THAT to a null.  Bottom line:  If the underlying native code were (for some reason) to return an empty (non-null) string, then I think this function should also return an empty (non-null) string.  That said, I agree that its current behavior of returning an empty (non-null) string when the underlying native code returns a null string is broken.

(2)  The test case calls Path.GetTempPath() which is not allowed on WinRT.  Use the idiom found in other tests involving:

    using (sqlite3 db = ugly.open(":memory:"))
    {
        name = "tmp" + db.query_scalar<string>("SELECT lower(hex(randomblob(16)));");
    }

**Comment by bordoley** [comment]
I can take a look at this probably tomorrow, but if not then most likely over the weekend. Looking at the code for [from_utf8](https://github.com/ericsink/SQLitePCL.raw/blob/master/src/cs/util.cs#L68), I'm actually a little surprised this bug occurs for the [pinvoke case](https://github.com/ericsink/SQLitePCL.raw/blob/master/src/cs/sqlite3_pinvoke.cs#L347). Any idea why NativeMethods.sqlite3_db_filename would return an IntPtr not equal to IntPtr.Zero?

**Comment by bordoley** [comment]
I dug into the SQLite code and it appears the SQLite documentation conflicts with the implementation. For reference, here is the sqlite implementation of  [sqlite3_db_filename](https://github.com/mackyle/sqlite/blob/c1445d369c3609cabf405080aa6333685800e36e/src/main.c#L3681). The underlying code calls [sqlite3DbNameToBtree](https://github.com/mackyle/sqlite/blob/777ec7f11fb92ce65a839d0652b0d85d06a8f41a/src/btree.c#L8892) which is documented to return empty if the database is in-memory or a TEMP database. This is confirmed by investigating the underlying call to [sqlite3PagerFilename](https://github.com/mackyle/sqlite/blob/d8ad470cb73bd6b5608f2248e8b458f05e9f43eb/src/pager.c#L6627).

**Comment by ericsink** [comment]
So it looks like there is no change here that we need to make?

**Comment by bordoley** [comment]
Yeah not a bug

**Pull request closed without merging**
