### PR TITLE
Genbuildvs

### PR DESCRIPTION
**Pull request by tofutim**
Please consider switching to a vs solution for gen_build, this PR also includes an option to generate the build files for a custom-named custom sqlite3. 

Still need to add snk generation and nuspecs.

### CODE REVIEW

**Comment by ericsink** [comment]
So, I suggested that if you didn't want to change the name of your DLL, you could probably get the bundle you want by examining how I build bundles and doing something similar.

And you've been digging in and getting your hands dirty.  That's good.

But I wasn't really expecting you to start working on a Pull Request that is effectively a rewrite of my build system.

Starting from the beginning:  You are wanting something like the ability to create a bundle, like the ones I've got, but with a customizable name for the SQLite library.  Do I want that feature?  Maybe.  I'm not sure.  It seems like very low bang for the buck when compared to the alternative, which is to simply use `custom_sqlite3` as the library name.  But if I had an implementation of that feature which is very low-risk, and which does not change the way I work in any substantial way?  Yeah, I could probably see that feature happening.

But this pull request does not *seem* to be heading in the direction of "minimal, low-risk, incremental change".

I thought I should express this reaction before you get too much further down the path you are on.  :-)

**Comment by tofutim** [comment]
If you prefer the single-file, csc build, I can move my changes back into
that framework when I'm done. Thanks for the notification.

**Comment by tofutim** [comment]
Pls consider the other two pull requests though. Just minimal changes.

**Comment by ericsink** [comment]
Yeah, I'll look at the others.  Heck, I'll be looking at this one too.  I won't rule out harvesting good ideas even though I don't want to make large changes.

Thanks.

**Comment by tofutim** [comment]
I think I can reframe this so that the VS solution/project sits in /src but
the gen_build.cs stays in the main directory and is compiled with csc if
you want. That way there are minimal changes for you but I can still take
advantage of VS.

Ignore that pull request for a bit.

**Comment by tofutim** [comment]
i'm going to try a baby step for you... ignore this PR

**Pull request closed without merging**
