### PR TITLE
Add .gitattributes and normalize all source files

### PR DESCRIPTION
**Pull request by sharwell**
* Add .gitattributes so users with different platforms and Git configurations experience consistent behavior
* Renormalize all source files to follow the common configuration (attributed to @ericsink to avoid be taking `git blame` ownership of the affected files)

⚠️ Use of a rebase or squash merge strategy may negatively impact the separation of content/authors in the individual commits of this pull request. It is designed for the standard "merge" strategy for git branches.

### CODE REVIEW

**Comment by ericsink** [comment]
Thanks for sending this. Initial reaction, looks good. I'll take a closer look soon and proceed.

**Comment by sharwell** [comment]
📝 In case you haven't seen it before, the renormalize command is:

```
git add --all --renormalize
```

**Comment by ericsink** [comment]
`--renormalize`:  That's good to know.

So to be honest, when I first saw this pull request come in, I was busy and could only glance at it.  Seeing that it was one of those "touch every file" requests, I started mentally drafting my note to explain why I would reject it.

Upon closer examination, none of my reasons seem to apply.  Impressive.  You even have it aimed at my v2 branch, which hardly anybody knows exists.

So now my curiosity is piqued.  What *else* are you up to w.r.t. SQLitePCL.raw?

You appear to be involved with Roslyn?  Is this related?  I've seen evidence here and there that something with SQLitePCL.raw might be going on with Roslyn, but I've never gotten a clear picture of what that was.

Thanks.

**Comment by sharwell** [comment]
I'm working on building up some benchmarks related to Roslyn's use of SQLite, and then determining if identified issues are things that can be improved in the interop layer and/or improved in Roslyn's use of the library.

**Pull request merged**
