### PR TITLE
Add support for linux-musl-s390x target

### PR DESCRIPTION
**Pull request by uweigand**
This implements the rest of https://github.com/ericsink/SQLitePCL.raw/issues/571, after the "cb" part (https://github.com/ericsink/cb/pull/21) is merged.

### CODE REVIEW

**Comment by ericsink** [comment]
The current failure is because `e_sqlite3mc` (which is a very recent addition to the `cb` build system) is not being built for `musl-s390x`.  I am not sure what it would take to address this, so for now I will just Cc @utelle

**Comment by uweigand** [comment]
Looks like this seems to be the only change needed: https://github.com/ericsink/cb/pull/22

**Comment by utelle** [comment]
> The current failure is because `e_sqlite3mc` (which is a very recent addition to the `cb` build system) is not being built for `musl-s390x`. I am not sure what it would take to address this, so for now I will just Cc @utelle

Sorry for the late response. I was away from home. Obviously, the problem is not related to _SQLite3 Multiple Ciphers_ itself, but to the build procedure in `cb.cs`. Maybe the build procedure could be improved by making the list of targets a global object, instead of defining it separately for each component (making it easy to forget to add new targets to **all** relevant lists). This would allow to change it for all components in sync.

**Comment by ericsink** [comment]
No worries.  It turned out to be an easy fix.

**Pull request merged**
