### PR TITLE
Support for Xamarin.Mac 2.0

### PR DESCRIPTION
**Pull request by nberardi**
This should fix issue #40.  This cannot be generated from a Windows box, it has to be run on a Mac, because Xamarin does support Mac as a remote build like iOS.  Just an FYI, incase you weren't aware.

### CODE REVIEW

**Comment by nberardi** [comment]
@bordoley Are you able to test this out and give me a sanity check?

**Comment by bordoley** [comment]
@nberardi I'm out of town til the weekend. It should be pretty easy to clone SQLitePCL.pretty and run the unit tests with your version. One thing that might need to happen is to create a new unit test project for xam unified mac.

**Comment by nberardi** [comment]
Any update on this? I am interested in getting this merged into my package using NuGet.  I was wondering if you needed anything more from my pull request?

**Comment by ericsink** [comment]
I've been traveling with very limited network access. Back in the office
next week.

E

**Comment by ericsink** [comment]
OK, I'm back online and trying to catch up.

A quick initial skim of your diff looks good.

I've gotta figure out what to do about builds though.  The main build of SQLitePCL.raw occurs on a Windows machine.

So you've run gen_build and generated the Xam.Mac stuff and  built it on a Mac and it works okay for you?

**Comment by nberardi** [comment]
I created a private build to work with sqlite-net-pcl while waiting for your to officially publish. The build I am using works great.

The only alternative I can really suggest for building if you don't have a Mac to hookup as a build agent for your server, is to let me do builds for you. 

Speaking of builds, do you have any interest in making the pre-build script easier to run.  Maybe a project, or at least a commandline tool to compile the C# into an exe to run.

**Comment by ericsink** [comment]
I do have a Mac.  I'm just trying to keep the build runnable in a single
step. Can't build a windows on a Mac. Can't build Mac on windows.  Etc.

E

**Comment by ericsink** [comment]
What command line would be simpler than the following?

csc gen_buiild.cs

E

**Comment by ericsink** [comment]
"This cannot be generated from a Windows box, it has to be run on a Mac, because Xamarin does support Mac as a remote build like iOS."

I gotta slow down.  I've read this sentence multiple times and I think I've read it wrong every time.

So if Xamarin does in fact do the remote build host things for Mac (like it does for iOS), then I've got no problem after all.

E

**Comment by nberardi** [comment]
I miss wrote the original. It should read as doesn't.

"This cannot be generated from a Windows box, it has to be run on a Mac, because Xamarin **doesn't** support Mac as a remote build like iOS."

As of right now, I don't think you can have the whole thing runnable on one machine.  It is a huge PITA that Xamarin doesn't support remote Mac builds.

**Comment by ericsink** [comment]
Ah, then I mis-read it the way you intended to write it.  Two wrongs make a right.

OK, I'll figure something out.  This is not without precedent.  For example, pre-built versions of SQLite for Mac are actually checked into the repo.  :-)

**Comment by ericsink** [comment]
Version 0.8.1-pre1 of the package (on nuget) contains this feature.  Would you have a chance to test it out?  Thanks!

**Pull request merged**
