### PR TITLE
nuspec fixes for #207

### PR DESCRIPTION
**Pull request by Therzok**
Packed the nupkg locally for the osx provider:
```
➜  bld git:(fix-207) unzip -d osx SQLitePCLRaw.lib.e_sqlite3.osx.1.1.10-pre20180314153929.nupkg
Archive:  SQLitePCLRaw.lib.e_sqlite3.osx.1.1.10-pre20180314153929.nupkg
  inflating: osx/_rels/.rels
  inflating: osx/SQLitePCLRaw.lib.e_sqlite3.osx.nuspec
  inflating: osx/runtimes/osx-x64/native/libe_sqlite3.dylib
  inflating: osx/build/net35/SQLitePCLRaw.lib.e_sqlite3.osx.targets
 extracting: osx/lib/Xamarin.Mac20/_._
  inflating: osx/build/Xamarin.Mac20/SQLitePCLRaw.lib.e_sqlite3.osx.targets
 extracting: osx/lib/net35/_._
 extracting: osx/lib/netstandard1.0/_._
 extracting: osx/lib/netstandard2.0/_._
  inflating: osx/[Content_Types].xml
  inflating: osx/package/services/metadata/core-properties/2b5cef130187491fa975753415526072.psmdcp
➜  bld git:(fix-207) cd osx
➜  osx git:(fix-207) ls
SQLitePCLRaw.lib.e_sqlite3.osx.nuspec build                                 runtimes
[Content_Types].xml                   lib
_rels                                 package
➜  osx git:(fix-207) cat build/net35/SQLitePCLRaw.lib.e_sqlite3.osx.targets
<?xml version="1.0" encoding="utf-8"?>
<!--Automatically generated-->
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target Name="InjectReference_95471b35-f1d8-47ef-9a65-3f10fca17884" BeforeTargets="ResolveAssemblyReferences">
    <ItemGroup Condition=" '$(OS)' == 'Unix' AND Exists('/Library/Frameworks') ">
      <Content Include="$(MSBuildThisFileDirectory)..\..\runtimes\osx-x64\native\libe_sqlite3.dylib">
        <Link>libe_sqlite3.dylib</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        <Pack>false</Pack>
      </Content>
    </ItemGroup>
  </Target>
  <PropertyGroup>
    <ResolveAssemblyReferencesDependsOn>$(ResolveAssemblyReferencesDependsOn);InjectReference_95471b35-f1d8-47ef-9a65-3f10fca17884</ResolveAssemblyReferencesDependsOn>
  </PropertyGroup>
</Project>

➜  osx git:(fix-207) cat build/Xamarin.Mac20/SQLitePCLRaw.lib.e_sqlite3.osx.targets
<?xml version="1.0" encoding="utf-8"?>
<!--Automatically generated-->
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target Name="InjectReference_89d9ce18-3174-469d-be96-55726fb2bc73" BeforeTargets="ResolveAssemblyReferences">
    <ItemGroup Condition=" '$(OS)' == 'Unix' AND Exists('/Library/Frameworks') ">
      <NativeReference Include="$(MSBuildThisFileDirectory)..\..\runtimes\osx-x64\native\libe_sqlite3.dylib">
        <Kind>Dynamic</Kind>
        <SmartLink>False</SmartLink>
      </NativeReference>
    </ItemGroup>
  </Target>
  <PropertyGroup>
    <ResolveAssemblyReferencesDependsOn>$(ResolveAssemblyReferencesDependsOn);InjectReference_89d9ce18-3174-469d-be96-55726fb2bc73</ResolveAssemblyReferencesDependsOn>
  </PropertyGroup>
</Project>
```

### CODE REVIEW

**Comment by Therzok** [comment]
```
➜  bld git:(fix-207) cat SQLitePCLRaw.lib.sqlcipher.osx.targets
<?xml version="1.0" encoding="utf-8"?>
<!--Automatically generated-->
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target Name="InjectReference_0efd37ca-7312-47a1-b9ce-ee0acc18bb5d" BeforeTargets="ResolveAssemblyReferences">
    <ItemGroup Condition=" '$(OS)' == 'Unix' AND Exists('/Library/Frameworks') ">
      <Content Include="$(MSBuildThisFileDirectory)..\..\runtimes\osx-x64\native\libsqlcipher.dylib">
        <Link>libsqlcipher.dylib</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        <Pack>false</Pack>
      </Content>
    </ItemGroup>
  </Target>
  <PropertyGroup>
    <ResolveAssemblyReferencesDependsOn>$(ResolveAssemblyReferencesDependsOn);InjectReference_0efd37ca-7312-47a1-b9ce-ee0acc18bb5d</ResolveAssemblyReferencesDependsOn>
  </PropertyGroup>
</Project>%                                                                                                                  ➜  bld git:(fix-207) cat SQLitePCLRaw.lib.sqlcipher.osx.Xamarin.Mac20.targets
<?xml version="1.0" encoding="utf-8"?>
<!--Automatically generated-->
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target Name="InjectReference_f2f9034c-c5a3-4204-afb8-dd27252d37c6" BeforeTargets="ResolveAssemblyReferences">
    <ItemGroup Condition=" '$(OS)' == 'Unix' AND Exists('/Library/Frameworks') ">
      <NativeReference Include="$(MSBuildThisFileDirectory)..\..\runtimes\osx-x64\native\libsqlcipher.dylib">
        <Kind>Dynamic</Kind>
        <SmartLink>False</SmartLink>
      </NativeReference>
    </ItemGroup>
  </Target>
  <PropertyGroup>
    <ResolveAssemblyReferencesDependsOn>$(ResolveAssemblyReferencesDependsOn);InjectReference_f2f9034c-c5a3-4204-afb8-dd27252d37c6</ResolveAssemblyReferencesDependsOn>
  </PropertyGroup>
</Project>%
```

Same for sqlcipher

**Comment by ericsink** [comment]
Nice work.  Thanks!

**Comment by Therzok** [comment]
Hope this works! I couldn't test out the nupkgs locally and co, but I imagine this is good enough.

**Comment by ericsink** [comment]
I think it's going to be fine.  I accidentally broke this behavior between 1.1.8 and 1.1.9.  I'd diffed your patch against both the 1.1.8 code and the 1.1.9 code, and it looks good as a combination of both approaches to the targets file.

**Pull request merged**
