### PR TITLE
Stmt status and progress handler

### PR DESCRIPTION
**Pull request by bordoley**
These two PRs actually merged cleanly so you can either pull from the individual PRs or from this one.

### CODE REVIEW

**Comment by ericsink** [comment]
The test case for sqlite3_stmt_status is failing (on my Windows machine).

Does it pass for you?

The first call to get SQLITE_STMTSTATUS_VM_STEP is apparently returning 0.

**Comment by bordoley** [comment]
It passed for me testing against the x86 net45 version. I'm using a Test
project that includes ugly.cs and test_cases.cs, and references the built
x86 debug build in bld/bin/x86/debug.

When I run the test I get the following (via the debugger):
  vmStep: 8
  vmStep2: 8
  vmStep3: 0

Dave

**Comment by ericsink** [comment]
Hmph.

**Comment by bordoley** [comment]
My cs proj might be using target files from the 0.7.1 release (I'll need to
check). Could that affect this at all?

Hmph.

—
Reply to this email directly or view it on GitHub
<https://github.com/ericsink/SQLitePCL.raw/pull/33#issuecomment-72055478>.

**Comment by ericsink** [comment]
The test fails when running the net45 tests in the main sqlitepcl.sln file, which contains a simple csproj that references the cppinterop version of the net45 assembly.

But if I separately create a unit test project for net45 and then add things from the nuget package, the test passes.

And using the same approach, it passes on iOS as well.

So either the sqlite3_stmt_status function is broken for cppinterop cases, or there is something funky about the unit test project which is generated for sqlitepcl.sln.  The fact that this is the only test that fails would seem to suggest (but not prove) the former.

**Comment by bordoley** [comment]
I'll take a look tonight. I'm fairly certain that I tested with the CPP
version when I first wrote the implementation but its possible I missed
something. A quick glimpse at the code didn't reveal anything obvious.

Dave

The test fails when running the net45 tests in the main sqlitepcl.sln file,
which contains a simple csproj that references the cppinterop version of
the net45 assembly.

But if I separately create a unit test project for net45 and then add
things from the nuget package, the test passes.

And using the same approach, it passes on iOS as well.

So either the sqlite3_stmt_status function is broken for cppinterop cases,
or there is something funky about the unit test project which is generated
for sqlitepcl.sln. The fact that this is the only test that fails would
seem to suggest (but not prove) the former.

—
Reply to this email directly or view it on GitHub
<https://github.com/ericsink/SQLitePCL.raw/pull/33#issuecomment-72061166>.

**Comment by ericsink** [comment]
Never mind.  The problem is specific to the test csproj in the sln file.  Thanks.

**Pull request merged**
