### PR TITLE
Add GitHub Actions run to build and test changes, fix macOS builds

### PR DESCRIPTION
**Pull request by filipnavara**

### CODE REVIEW

**Comment by filipnavara** [comment]
I don't think this will run on a PR from a fork due to security precautions. The same thing was tested on a fork at https://github.com/emclient/SQLitePCL.raw/pull/2/checks.

**Comment by filipnavara** [comment]
I've also added macOS build and fixed it. It supersedes #363.

**Comment by ericsink** [comment]
OK so this is very cool.

I haven't setup GitHub Actions for this project because I haven't taken the time to understand it.

Now I have two choices:

(1) Merge this without understanding it.
(2) Understand it, and then merge it.

And then there are two sub-choices:

(2a) Understand it by reading
(2b) Understand it by asking @filipnavara clueless questions.

So, er, yeah, some of (2b) might happen.

**Comment by ericsink** [comment]
Sorry for the delay on this.  I haven't forgotten it.  :-)

**Comment by ericsink** [comment]
@filipnavara I don't suppose you would like to do this GitHub Actions thing for my ericsink/cb repo?  <cheesy_grin/>

**Comment by filipnavara** [comment]
I was actually thinking about it. Not sure when I would get to do it though (unless the weather is bad on a weekend)...

**Comment by filipnavara** [comment]
I've started some early experiment with building `cb` with GitHub Action here: https://github.com/filipnavara/cb/pull/1. It's about 30% done (no Windows, Android yet; no uploads besides artifact .zip files).

**Pull request merged**
