### PR TITLE
Use FluentAssertions instead of xUnit assertions

### PR DESCRIPTION
**Pull request by 0xced**
FluentAssertions is much more expressive than xUnit assertions. It also gives much better error messages when the assertions fail. For example:

```
FluentAssertions.Execution.AssertionFailedException: Expected v.Kind to be Utc, but found Unspecified.
```

The assertions have been reviewed manually to match the most expressive fluent assertion equivalents. For example `Assert.True(result > 0)` has been translated to `result.Should().BeGreaterThan(0)` instead of `(result > 0).Should().BeTrue()` in order to get the best possible assertion failure messages.

Finally, by using FluentAssertions, we can get rid of the Xunit.Assert static class in fake_xunit. The number of asserts for a given test has been lost, but let's hope a solution to this might exist, see [How to count the number of assertions inside an AssertionScope?][1].

[1]: https://github.com/fluentassertions/fluentassertions/issues/1380

### CODE REVIEW

**Comment by ericsink** [comment]
I'm rather unsure about this one.  I mean, yes, I like FluentAssertions as a concept, but adding a dependency always makes me worry about future hassles.

**Comment by 0xced** [comment]
Well, the error messages when an assertion fails are so good that I think it's worth adding a dependency. Also, it's a dependency for the *tests* only. I'm usually less concerned about adding dependencies for test projects but the final call is up to you.

Also, **many** assertions are much easier to read (and write) thanks to FluentAssertions *Should()* magic of handling nulls.

Before:
```csharp
var v = stmt.column<int?>(0);
Assert.True(v.HasValue);		
Assert.Equal(32, v);
```

After:
```csharp
stmt.column<int?>(0).Should().Be(32);
```

If null is returned, FluentAssertions properly handles it with this AssertionFailedException: `Expected value to be 32, but found <null>.`

**Comment by dennisdoomen** [comment]
> but adding a dependency always makes me worry about future hassles

An extra dependency on your unit testing project? What kind of future hassle is that?

**Comment by ericsink** [comment]
> An extra dependency on your unit testing project? What kind of future hassle is that?

I think I'll assume this is a serious question.

For this particular project, I have an aversion to dependencies that is probably higher than most folks.  All dependencies are guilty until proven innocent.  This stance has served me very well.

That said, I'll admit that a dependency which affects only the testing parts of this project is not as likely to be much of an issue.  For that reason, this PR still tempts me a bit.

But even xUnit itself has been so much trouble.  SQLitePCLRaw is mostly a wrapper around native code, and that makes everything more complicated.  I got so tired of dealing with xUnit situations where it couldn't find the native library that I write fake_xunit.  This PR makes a big change to that code, so I would need to review it.

Like I said, I like what I see in fluent assertions, so I may yet take the time to consider this more carefully.  But still, this PR addresses an issue where I have not been dissatisfied with the status quo, so I've had trouble finding the time and motivation to deal with it.

**Comment by dennisdoomen** [comment]
I understand your pain. Thank you for taking the time to clarify this.

**Comment by 0xced** [comment]
Thank you for your thoughtful reply, Eric.

Let me just show this very compelling exemple in favor of FluentAssertions (somewhat related to #362). 😉

```csharp
var v = stmt.column<DateTime>(0);
Assert.Equal(1968, v.Year);
Assert.Equal(3, v.Month);
Assert.Equal(15, v.Day);
Assert.Equal(0, v.Hour);
Assert.Equal(0, v.Minute);
Assert.Equal(0, v.Second);
Assert.Equal(0, v.Millisecond);
// Can't use Assert.Equal on a DateTimeKind enum because fake_xunit's Assert.Equal<T> has a constraint on "T : class" that xunit doesn't have
Assert.Equal((int)DateTimeKind.Utc, (int)v.Kind);
```

vs

```csharp
stmt.column<DateTime>(0).Should().Be(new DateTime(1968, 3, 15, 0, 0, 0)).And.BeIn(DateTimeKind.Utc);
```

By the way, in xUnit 3, test projects are going to be [programs instead of libraries](https://github.com/xunit/xunit/issues/2133#issuecomment-674344404). This might or might not improve the situation with loading native libraries… 🤞🏻

**Comment by ericsink** [comment]
It's probably time for me to admit it:  Perhaps there is something wrong with me, but I don't find the example above to be "compelling".  :-)

**Comment by dennisdoomen** [comment]
Actually, it should have been written as:

`stmt.column<DateTime>(0).Should().Be(15.March(1968).At(0.Hours(0)).And.BeIn(DateTimeKind.Utc);`

**Comment by 0xced** [comment]
The real selling point for me is the quality of the error messages when the assertions fail. xUnit's assertion messages are pretty bad compared to FluentAssertions.

And having autocompletion after you type `Should()` is really nice too.

**Pull request closed without merging**
