### PR TITLE
Support sqlite3_table_column_metadata.

### PR DESCRIPTION
**Pull request by bordoley**
Work in progress. I will add unit tests. I was wondering if you could provide me feedback/examples on the best way to pass "out int" parameters to the cpp implementation .  I didn't see any other examples of APIs with "out int" in the library.

### CODE REVIEW

**Comment by bordoley** [comment]
This is actually complete as i recall if you have time to look into it.

**Comment by ericsink** [comment]
I'll get to this one as soon as I can.  I'm currently dragging my feet a little bit on any PR which takes manual merge work.  :-)

**Comment by bordoley** [comment]
I might have some time tonight to forward merge my branch to master.

Dave

**Comment by bordoley** [comment]
Updated to resolve merge conflicts (git rebased)

**Pull request merged**
